Hw06 pipeline execution
pyltsin/otusGolang pull request #10
Opened 2020-10-17 20:46 UTC by pyltsin

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-10-18 13:48 UTC, kulti requested changes
Честно говоря, не сразу понял, что именно вы захотели "усложнить". Если правильно разобрался, то запускается несколько стейджей каждого типа, чтобы обрабатывать больше одного задания за раз.

Получилось довольно сложно. Рекомендую решить исходную задачу и подумать, как можно использовать ExecutePipeline, чтобы получить тот же эффект.

Если не будет идей, то напишите мне в слаке, обсудим. Пока подскажу примерные размеры решения. Последовательный ExecutePipeline решается строк в 40, а доделка до желаемой параллельности это еще примерно 10 строк.

2020-10-19 07:27 UTC, kulti approved these changes
В решение есть ошибки.

Также в коде много комментариев из-за того, что он непонятный — явный признак не очень хорошего кода. Логирование внутри библиотечных вызовов тоже так себе практика, т.к. такую библиотеку нельзя переиспользовать из-за мусорных сообщений.

ДЗ сделано не по заданию. Обсудили в слаке, что это это эксперимент. ДЗ принимаю на 7/10.

2020-10-19 07:27 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		out <- message
Эти записи и чтения из каналов выглядят довольно опасно. Если я правильно распутал клубок из горутин и каналов, то тут все может зависнуть.

Например, стейдж, который должен читать из out больше этого не делает, т.к. завершился по done.

2020-10-19 07:35 UTC, pyltsin commented on hw06_pipeline_execution/pipeline.go
> +		var wg sync.WaitGroup
Комментарий согласен не очень верен. Мы ждём завершения дочерних горутин. И потом закрываем выходной канал

2020-10-19 07:35 UTC, pyltsin commented on hw06_pipeline_execution/pipeline.go
> +		for nextValue := range in {
На это есть тест. Все закроется корректно, так как закрывает только тот кто имеет право

2020-10-19 07:36 UTC, pyltsin commented on hw06_pipeline_execution/pipeline.go
> +		}(funIn, messageOut)
Согласен, можно и на замыкании

2020-10-19 07:36 UTC, pyltsin commented on hw06_pipeline_execution/pipeline.go
> +		out <- message
Это просто обертка для stage. Все закрытия каналов реализовано выше и закрывается корректно

2020-10-19 07:47 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		for nextValue := range in {
Я о том, что тут все зависнет. В in больше не пишут, но и не закрывают — в этом случае range зависнет навсегда.

Наверно, в неудачном месте этот комментарий оставил. Этот "паттерн" встречается по всему коду. Проблема начнется в методе convertMessage.

2020-10-19 07:49 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		out <- message
Вы про потенциальную запись в закрытый канал? С этим, вроде, все хорошо. Я же про то, что тут может быть запись в канал, из которого никто не читает.

2020-10-19 08:16 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		for nextValue := range in {
Для проверки, можете в тесте "done case" убрать горутину с закрытием done и заменить закрытие in на закрытие done.

Все может выглядеть "рабочим", т.к. нет ожидания завершения горутины в convertMessage. Не фикся это, можно добавить слип в конец теста и почитать логи.

2020-10-19 12:18 UTC, pyltsin commented on hw06_pipeline_execution/pipeline.go
> +		for nextValue := range in {
Понял вас, спасибо - брал этот паттерн из занятия - там таким образом закрывались значения - думал, что стандарт

2020-10-31 13:17 UTC, merged