Домашнее задание №9 «Валидатор структур»
pyltsin/otusGolang pull request #13
Opened 2020-11-14 15:57 UTC by pyltsin

## Домашнее задание №9 «Валидатор структур»

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-11-18 06:03 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/974/8090/

Здравствуйте!
Аккуратный, приятный код. Но много вопросов

Предварительно
5 / 10

2020-11-18 06:03 UTC, Antonboom commented on hw09_struct_validator/validator.go
> +			ValidationError{Field: "", Err: fmt.Errorf("can not parse validate tag: %s", typeValue.Tag)})
это не выглядит как ValidationError + тэга может не быть, по ТЗ мы его пропускаем: такие тесты есть?

2020-11-18 06:03 UTC, Antonboom commented on hw09_struct_validator/validator.go
> +			inVal, err := strconv.Atoi(inString)
`ParseInt` и сразу в int64

2020-11-18 06:03 UTC, Antonboom commented on hw09_struct_validator/validator_test.go
> +			assert.Equal(t, tt.countError, len(validate))
не хватает:
- ассертов и тестов на программную ошибку (error)
- ассертов на ValidationError, с проверкой имён полей и конкретных ошибок-значений внутри

2020-11-19 16:58 UTC, pyltsin commented on hw09_struct_validator/go.mod
> +go 1.14
Исправлено

2020-11-19 16:58 UTC, pyltsin commented on hw09_struct_validator/validator.go
> +		sb.WriteString(fmt.Sprintf("Error %s for field %s \n", err.Err, err.Field))
исправил по статье https://yourbasic.org/golang/build-append-concatenate-strings-efficiently/

2020-11-19 17:04 UTC, pyltsin commented on hw09_struct_validator/validator.go
> +	for i := 0; i < valueV.NumField(); i++ {
Добавлено

2020-11-19 17:08 UTC, pyltsin commented on hw09_struct_validator/validator.go
> +		errors = append(errors, err...)
Здесь не нужно.
 Так как 
	var errors ValidationErrors
	var err ValidationErrors
	errors = append(errors, err...)
	assert.Equal(t, 0, len(errors))
	var err2 = ValidationErrors{
		ValidationError{Err: NotStructError, Field: ""},
	}
	errors = append(errors, err2...)
	assert.Equal(t, 1, len(errors))

Позитивные тесты :
- 		{Response{Code: 200, Body: ""}, 0},
-  		{App{Version: "12345"}, 0},
- 		{User{ID: "123456789012345678901234567890123456", Name: "", Age: 20, Email: "test@test.ru", Role: "admin", Phones: []string{"12345678901"}, meta: nil}, 0},

2020-11-19 17:28 UTC, pyltsin commented on hw09_struct_validator/validator.go
> +				ValidationError{Field: typeValue.Name, Err: fmt.Errorf("%v not in %s", strValue, inValueString)})
Добавлено

2020-11-19 17:35 UTC, pyltsin commented on hw09_struct_validator/validator.go
> +		var re = regexp.MustCompile(r)
Добавлено

2020-11-19 17:43 UTC, pyltsin commented on hw09_struct_validator/validator.go
> +			inVal, err := strconv.Atoi(inString)
Исправил

2020-11-19 17:55 UTC, pyltsin commented on hw09_struct_validator/validator.go
> +			ValidationError{Field: "", Err: fmt.Errorf("can not parse validate tag: %s", typeValue.Tag)})
Так и работало, ok - сигнализирует, что тэг `validate` содержит что-то не по формату, если validate нет, то пропускаем и ok=true

2020-11-19 18:09 UTC, pyltsin commented on hw09_struct_validator/validator_test.go
> +			assert.Equal(t, tt.countError, len(validate))
Добавлены тесты

2020-11-20 06:43 UTC, Antonboom approved these changes
Отличная работа!

10 / 10

2020-11-20 21:04 UTC, merged