Hw10 program optimization
pyltsin/otusGolang pull request #14
Opened 2020-11-20 21:07 UTC by pyltsin

## Домашнее задание №10 «Оптимизация программы»

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-11-20 23:21 UTC, kulti requested changes
Хорошее решение. Все необходимые места соптимизированны.

В решение есть ошибка и немного грязного кода. Предлагаю это все поправить.

2020-11-20 23:21 UTC, kulti commented on hw10_program_optimization/stats.go
> +		}
От начала цикла и до этого места можно написать намного проще, если использовать bufio.Scanner.

2020-11-20 23:21 UTC, kulti commented on hw10_program_optimization/stats.go
> +		err = unmarshal(bytes, &user)
Переиспользовать user хорошая практика (если она дает выигрыш). Тогда нужно обязательно его обнулять. Иначе в нем останутся поля от предыдущего анмаршалинга.

https://goplay.space/#ERxN-OpXG4o

2020-11-20 23:21 UTC, kulti commented on hw10_program_optimization/stats.go
>  		}
Вместо этих 6 строк можно просто `result[domain]++`.

2020-11-20 23:21 UTC, kulti commented on hw10_program_optimization/stats_easyjson.go
> +// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.
FYI easyjson уже не самый быстрый. Есть https://github.com/json-iterator/go, для которого, к тому же, не нужна кодогенерация.

2020-11-21 17:38 UTC, pyltsin commented on hw10_program_optimization/stats.go
> +		}
исправлено, спасибо, забыл

2020-11-21 17:41 UTC, pyltsin commented on hw10_program_optimization/stats.go
> +		err = unmarshal(bytes, &user)
Спасибо! добавил сброс email

2020-11-21 17:41 UTC, pyltsin commented on hw10_program_optimization/stats.go
>  		}
сделано

2020-11-21 17:43 UTC, pyltsin commented on hw10_program_optimization/stats_easyjson.go
> +// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.
Спасибо, не знал, easyjson - просто давно хотел его попробовать, пока оставил его, для задания хватает)

2020-11-22 16:16 UTC, kulti approved these changes

2020-11-22 16:16 UTC, kulti commented
Теперь все корректно. ДЗ принято - 10/10.

2020-11-30 19:42 UTC, merged