hw11_telnet_client
pyltsin/otusGolang pull request #15
Opened 2020-11-30 19:35 UTC by pyltsin

## Домашнее задание №11 «Клиент TELNET»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 4 баллов

#### Зачёт от 7 баллов

2020-12-04 07:19 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	signals          = make(chan os.Signal, 1)
лучше не выносить переменные на глобальный уровень, даже на уровне одного пакета

2020-12-04 07:24 UTC, balabanovds commented on hw11_telnet_client/main.go
> +		log.Fatal(ErrNotEnoughArgs)
можно выводить более информативно - например кастомизировать flag.Usage

2020-12-04 07:26 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	ErrNotEnoughArgs = errors.New("should be 3 at least")
почему переменная экспортируется? Вы же не либу пишете, а бинарь

2020-12-04 07:52 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	port := os.Args[3]
если запускать без флага, будет паника
$ ./t localhost 4242<div>panic: runtime error: index out of range [3] with length 3</div><div><br></div>

2020-12-04 08:05 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	"flag"
если строго придерживаться задания, то там сказано что аргумент должен быть `--timeout` 
стандартная либа flag поддерживает только одно тире - можно использовать pflag

2020-12-04 08:16 UTC, balabanovds commented on hw11_telnet_client/telnet.go
> +func NewTelnetClient(address string, timeout time.Duration, in io.ReadCloser, out io.Writer) TelnetClient {
конструктор лучше размещать ближе к описанию структуры

2020-12-04 08:23 UTC, balabanovds commented on hw11_telnet_client/telnet.go
> +	_, err := io.Copy(c.conn, c.in)
нет обработки нескольких важных моментов:
- При нажатии `Ctrl+D` программа должна закрывать сокет и завершаться с сообщением.
- Если сокет закрылся со стороны сервера, то при следующей попытке отправить сообщение программа <span style="font-family: var(--font-family); color: var(--text-color); font-weight: var(--font-weight);">должна завершаться (допускается завершать программу после "неудачной" отправки нескольких сообщений).

Подсказка:  `bufio`</span>

2020-12-04 08:26 UTC, balabanovds commented on hw11_telnet_client/telnet_test.go
> +	})
было бы неплохо добавить тест на кейс, когда клиент должен завершаться по  `Ctrl+D`

2020-12-04 08:37 UTC, balabanovds requested changes
Хорошая работа, но не реализует два требования:
- обработка `Ctrl+D`
- попытка писать в закрытое удаленным сервером соединение

Предлагаю Вам подумать над реализацией, если будут вопросы, то я доступен в Slack.
Пока оценка 6/10

Успехов!

2020-12-04 19:32 UTC, pyltsin commented on hw11_telnet_client/main.go
> +	signals          = make(chan os.Signal, 1)
Исправлено

2020-12-04 19:38 UTC, pyltsin commented on hw11_telnet_client/main.go
> +	ErrNotEnoughArgs = errors.New("should be 3 at least")
Исправлено

2020-12-04 19:50 UTC, pyltsin commented on hw11_telnet_client/main.go
> +	port := os.Args[3]
Исправлено

2020-12-04 19:50 UTC, pyltsin commented on hw11_telnet_client/telnet.go
> +func NewTelnetClient(address string, timeout time.Duration, in io.ReadCloser, out io.Writer) TelnetClient {
Исправлено

2020-12-04 20:02 UTC, pyltsin commented on hw11_telnet_client/telnet.go
> +	_, err := io.Copy(c.conn, c.in)
Исправлено

2020-12-04 20:33 UTC, pyltsin commented on hw11_telnet_client/main.go
> +	"flag"
у меня отрабатывает на двух - спокойно)

2020-12-04 20:56 UTC, pyltsin commented on hw11_telnet_client/telnet_test.go
> +	})
Кажется, добавил

2020-12-05 08:39 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	port := os.Args[3]
можно проще flag.NArg

2020-12-05 08:49 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	"flag"
да, включили во flag парсинг с двумя дефисами, раньше не было

2020-12-05 08:56 UTC, balabanovds commented on hw11_telnet_client/telnet.go
> +	_, err := io.Copy(c.conn, c.in)
при нажатии `Ctrl+D` программа должна завершаться сообщениемтакже добавьте эту проверку в тест кейс

2020-12-05 08:57 UTC, balabanovds commented on hw11_telnet_client/telnet_test.go
> +	})
добавьте проверку на вывод сообщения

2020-12-05 09:05 UTC, balabanovds reviewed
Хорошо получилось!Но давайте еще убедимся что тест на `Ctrl+D` отрабатывает верноВ задании написано что при `Ctrl+D` клиент должен завершаться с сообщением.Предлагаю в этом убедиться

2020-12-05 12:38 UTC, pyltsin commented on hw11_telnet_client/telnet_test.go
> +	})
Добавлено

2020-12-05 12:38 UTC, pyltsin commented on hw11_telnet_client/telnet.go
> +	_, err := io.Copy(c.conn, c.in)
Добавлено

2020-12-05 15:20 UTC, balabanovds approved these changes
Отлично! 10/10

Спасибо за работу! Успехов!

2020-12-06 19:22 UTC, merged